services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
    ports:
      - 8081:8000
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --reload
