services:
  python-dev:
    build:
      context: .
      dockerfile: docker/dev/python.dev.dockerfile
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
    ports:
      - 8081:8000
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --reload

  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx.dockerfile
    ports:
      - 8081:80
    depends_on:
      - python

  python:
    build:
      context: .
      dockerfile: docker/prod/python.dockerfile
    container_name: try_fastapi-python
    ports:
      - 8000:8000
